Fix error.
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.AnimalTamer.getName()" because the return value of "org.bukkit.entity.Tameable.getOwner()" is null